FROM amd64/node:alpine

RUN apk --no-cache --update add jq curl bash nodejs-current npm procps

WORKDIR /server

COPY mms-docker /server/

RUN npm install -g npm@8.1.3
RUN npm install

CMD ["npm", "start"]