FROM node:16.3.0

RUN apt-get update -y && apt-get install -y apt-utils && apt-get install vim -y

WORKDIR /server

COPY mms-docker /server/

RUN npm install -g npm
RUN npm install

CMD ["npm", "start"]
